/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graficos;

import javax.swing.JFrame;

/**
 *
 * @author José
 */
public class Score extends javax.swing.JFrame {

    /**
     * Creates new form Score
     */
    public Score() {
        initComponents();
        setLocationRelativeTo(null);//Ajusta la ventana al centro del escritorio
        this.setSize(410, 340);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);//Opcion por defecto para cerrar la ventana
        setResizable(false);//Impedir el reajuste de la pantalla
        jLabel3.setText(Juego.puntuacion.toString());
        nombre.setText(Juego.nombre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        cabecera = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        dificultad = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        modo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cabecera.setBackground(new java.awt.Color(0, 0, 0));
        cabecera.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        cabecera.setForeground(new java.awt.Color(255, 51, 51));
        cabecera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/salva.png"))); // NOI18N
        cabecera.setText(" DAW INVADERS");
        cabecera.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        getContentPane().add(cabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 413, 86));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 51));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/jugadorChiri.png"))); // NOI18N
        jButton2.setText("Reiniciar!!!");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 200, 50));

        jLabel1.setBackground(new java.awt.Color(51, 102, 255));
        jLabel1.setFont(new java.awt.Font("FreeSans", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/disparo.png"))); // NOI18N
        jLabel1.setText("Seleccione el grado de dificultad");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        dificultad.setBackground(new java.awt.Color(255, 51, 51));
        dificultad.setFont(new java.awt.Font("Chilanka", 1, 14)); // NOI18N
        dificultad.setForeground(new java.awt.Color(159, 8, 39));
        dificultad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fácil", "Medio", "Dificil", "DAW" }));
        dificultad.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        dificultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dificultadActionPerformed(evt);
            }
        });
        getContentPane().add(dificultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/gabriel.png"))); // NOI18N
        jLabel11.setText("Seleccione el modo de juego");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

        modo.setBackground(new java.awt.Color(255, 255, 51));
        modo.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        modo.setForeground(new java.awt.Color(255, 51, 0));
        modo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alumno", "Profesor", "Clasico" }));
        getContentPane().add(modo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconoDaw.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 30, 40));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconoDaw.png"))); // NOI18N
        jLabel13.setText("jLabel12");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 30, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("PUNTUACION");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 122, 39));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 0));
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 128, 39));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("By...Devas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondoInterfaz.jpg"))); // NOI18N
        jLabel5.setText("jLabel4");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, -20, 280, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondoInterfaz.jpg"))); // NOI18N
        jLabel6.setText("jLabel4");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 280, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondoInterfaz.jpg"))); // NOI18N
        jLabel7.setText("jLabel4");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 280, -1));

        nombre.setFont(new java.awt.Font("Rekha", 1, 18)); // NOI18N
        nombre.setForeground(new java.awt.Color(223, 249, 17));
        nombre.setText("jLabel9");
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 230, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondoInterfaz.jpg"))); // NOI18N
        jLabel9.setText("jLabel4");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 280, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondoInterfaz.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // boton comenzar
        //MODO ALUMNO
        if (dificultad.getSelectedItem().equals("Fácil") && modo.getSelectedItem().equals("Alumno")) {
            new Pantalla(Dificultad.FACIL, Juego.nombre, Modo.MODO_ALUMNO);
        }
        if (dificultad.getSelectedItem().equals("Medio") && modo.getSelectedItem().equals("Alumno")) {
            new Pantalla(Dificultad.MEDIO, Juego.nombre, Modo.MODO_ALUMNO);
        }
        if (dificultad.getSelectedItem().equals("Dificil") && modo.getSelectedItem().equals("Alumno")) {
            new Pantalla(Dificultad.DIFICIL, Juego.nombre, Modo.MODO_ALUMNO);
        }
        if (dificultad.getSelectedItem().equals("DAW") && modo.getSelectedItem().equals("Alumno")) {
            new Pantalla(Dificultad.DAW, Juego.nombre, Modo.MODO_ALUMNO);
        }
        //MODO PROFESOR
        if (dificultad.getSelectedItem().equals("Fácil") && modo.getSelectedItem().equals("Profesor")) {
            new Pantalla(Dificultad.FACIL, Juego.nombre, Modo.MODO_PROFESOR);
        }
        if (dificultad.getSelectedItem().equals("Medio") && modo.getSelectedItem().equals("Profesor")) {
            new Pantalla(Dificultad.MEDIO, Juego.nombre, Modo.MODO_PROFESOR);
        }
        if (dificultad.getSelectedItem().equals("Dificil") && modo.getSelectedItem().equals("Profesor")) {
            new Pantalla(Dificultad.DIFICIL, Juego.nombre, Modo.MODO_PROFESOR);
        }
        if (dificultad.getSelectedItem().equals("DAW") && modo.getSelectedItem().equals("Profesor")) {
            new Pantalla(Dificultad.DAW, Juego.nombre, Modo.MODO_PROFESOR);
        }
        //MODO CLASICO
        if (dificultad.getSelectedItem().equals("Fácil") && modo.getSelectedItem().equals("Clasico")) {
            new Pantalla(Dificultad.FACIL, Juego.nombre, Modo.MODO_CLASICO);
        }
        if (dificultad.getSelectedItem().equals("Medio") && modo.getSelectedItem().equals("Clasico")) {
            new Pantalla(Dificultad.MEDIO,Juego.nombre, Modo.MODO_CLASICO);
        }
        if (dificultad.getSelectedItem().equals("Dificil") && modo.getSelectedItem().equals("Clasico")) {
            new Pantalla(Dificultad.DIFICIL, Juego.nombre, Modo.MODO_CLASICO);
        }
        if (dificultad.getSelectedItem().equals("DAW") && modo.getSelectedItem().equals("Clasico")) {
            new Pantalla(Dificultad.DAW,Juego.nombre, Modo.MODO_CLASICO);
        }
       
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void dificultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dificultadActionPerformed

        // DIFICULTAD
    }//GEN-LAST:event_dificultadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cabecera;
    private javax.swing.JComboBox<String> dificultad;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> modo;
    private javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables
}
